EEE
======================================================================
ERROR: test_convertToBoolean (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_main.py", line 31, in test_convertToBoolean
    with self.subTest(key="Normal Input Test"):
AttributeError: 'Tests' object has no attribute 'subTest'

======================================================================
ERROR: test_convertToInteger (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_main.py", line 41, in test_convertToInteger
    with self.subTest(key="Normal Input Test"):
AttributeError: 'Tests' object has no attribute 'subTest'

======================================================================
ERROR: test_getStreakProduct (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_main.py", line 17, in test_getStreakProduct
    with self.subTest(key="9144576"):
AttributeError: 'Tests' object has no attribute 'subTest'

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (errors=3)
